# Generated by Django 6.1.1 on 2026-10-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_db',
            fields=[
                ('license_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('faults_found', models.TextField()),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_contact', models.IntegerField()),
                ('owner_address', models.TextField()),
                ('deposit_payed', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
